# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('observation', models.TextField()),
                ('tracked_on', models.DateTimeField()),
                ('audited', models.BooleanField(default=False)),
            ],
        ),
    ]
